### ISSUE TITLE
Is there a way to change the output text?

### ISSUE THREAD

**Issue by rvnerd** [copleykj/meteor-livestamp#16]
Could one pass optional parameters to change to outputted text?
For instance, instead of "3 minutes ago", be "3m ago" or just "3m"... 
Thanks for the awesome package.

**Comment by copleykj** [comment]
This isn't possible, but isn't due to this package. You might file a feature request on the original repository. https://github.com/mattbradley/livestampjs

**Comment by rvnerd** [comment]
thanks for the brief response =)
